### PR TITLE
Migrate to pnpm and remove tslint dependency

### PR DESCRIPTION
**Pull request by sentientmachin3**
- Removed tslint from dependencies, ESLint is installed and TSLint is deprecated.
- Migrated from NPM to PNPM which is faster and more efficient overall.

### CODE REVIEW

**Comment by spicemc** [comment]
Thanks for your contribution. I think it is possible to move to pnpm since i dropped support for NodeJS 12. 
But we should consider to have working GitHub-Workflows (including running pnpm actions) and the package.json scripts must also be adapted. If you can provide these changes to the PR would be great.

**Comment by sentientmachin3** [comment]
Sure, I'm not very familiar with github actions but I'll take a look.

**Comment by sentientmachin3** [comment]
Should be ok, check it out.

**Comment by spicemc** [comment]
All actions and checks failed.
I guess `- uses: pnpm/action-setup@v2` is needed after `- uses: actions/setup-node@v3`. I found it [here](https://github.com/pnpm/action-setup).
And the equivalent to `npm ci` is `pnpm install --frozen-lockfile`.

**Comment by sentientmachin3** [comment]
What's the matter? It appears to be an error related to `qs` not being found, but it's not in the package.json.

**Comment by spicemc** [comment]
Really strange. qs is missing in the dev dependencies, but it was never included. I don't know why this error doesn't show up with npm test.

**Comment by spicemc** [comment]
I guess qs is in the package-lock.json, but it is missing in the package.json. pnpm's lock file is completely created from scratch. Adding qs to the dev dependencies in the package.json should fix it.

**Comment by sentientmachin3** [comment]
Probably. I'll check this tonight.

**Comment by sentientmachin3** [comment]
All the tests pass now.

**Comment by sentientmachin3** [comment]
I saw the PR [here](https://github.com/typestack/routing-controllers/pull/933) on the original repo, I think I'll close this one and propose the changes over there.

**Pull request closed without merging**
